GET http://localhost:3000/

###

POST http://localhost:3000/users/submit
content-type: application/json

{
  "name": "hellomyname",
  "age": 50,
  "email": "hellosilver@world.com"
}

###
POST http://localhost:3000/users/submit
Content-Type: application/x-www-form-urlencoded

name=gold
&age=49


###
GET http://localhost:3000/users?page=-1&limit=3

###
GET http://localhost:3000/users?page=1&limit=1000

###
GET http://localhost:3000/users?page=1

###
GET http://localhost:3000/users?limit=5

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/100

###
DELETE http://localhost:3000/users/100


###
PUT http://localhost:3000/users/5
content-type: application/json

{
  "name": "silverdark6",
  "email": "hellosilver6@world.com",
  "age": 12
}